### ISSUE TITLE
Uglification

### ISSUE THREAD

**Issue by privatenumber** [egoist/vue-compile#5]
Very cool idea @egoist 

This would make it a lot easier for Vue developers to publish components (a lot of the tooling out there seems to be more tailored for apps).

I'm interested in being able to produce an uglified SFC file.

**Comment by egoist** [comment]
> This would make it a lot easier for Vue developers to publish components

Why do we need to uglify components?

**Comment by privatenumber** [comment]
Smaller distribution file

**Comment by egoist** [comment]
but that's a bad news for debugging?

**Comment by egoist** [comment]
And I don't see any advantages that smaller distribution file could bring us, maybe slightly faster `npm install`?

**Comment by privatenumber** [comment]
I felt we're past the debugging aspect since it's precompiled code but you're right. I thought about it some more and there isn't much of an advantage to uglification here I suppose.

Thanks for thinking about it!
