### ISSUE TITLE
[Feature Request] Support vue-compile --watch

### ISSUE THREAD

**Issue by ulivz** [egoist/vue-compile#9]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/vue-compile/issues/9)

Thanks for the excellent work!

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Sponsors (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/vue-compile/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by mesqueeb** [comment]
+1 : )

**Comment by mesqueeb** [comment]
@egoist IssueHunt says you didn't claim that 100 usd yet...?
